### ISSUE TITLE
help for install

### ISSUE THREAD

**Issue by nlienard** [ReneTode/Foscam-app#1]
Hello

My camera is F19821W V2

After installing appdaemon 3 and the 2 files in apps folder, i got the following error:

```
2018-03-01 13:31:10.059710 INFO AppDaemon: Loading Module: /home/thoht/.homeassistant/appdaemon/apps/foscam.py
2018-03-01 13:31:10.089647 WARNING AppDaemon: ------------------------------------------------------------
2018-03-01 13:31:10.090427 WARNING AppDaemon: Unexpected error loading module: /home/thoht/.homeassistant/appdaemon/apps/foscam.py:
2018-03-01 13:31:10.090935 WARNING AppDaemon: ------------------------------------------------------------
2018-03-01 13:31:10.100301 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1773, in check_app_updates
    self.read_app(mod["name"], mod["reload"])
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1650, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/thoht/.homeassistant/appdaemon/apps/foscam.py", line 518
    '    - spacer(2x1), spacer(2x1),' + self.recording_sensor + ', ' + self.      '    title: ' + self.camera_name,
                                                                                              ^
SyntaxError: invalid syntax

2018-03-01 13:31:10.101123 WARNING AppDaemon: ------------------------------------------------------------
2018-03-01 13:31:10.101615 WARNING AppDaemon: Removing associated apps:
2018-03-01 13:31:10.102129 WARNING AppDaemon: foscam
2018-03-01 13:31:10.103928 INFO AppDaemon: App initialization complete
```

**Comment by nlienard** [comment]
OK i guess the file was corrupted, i re-downloaded it.
Now it starts but still errors:

```
thoht@osmc:~/.homeassistant/appdaemon/conf$ appdaemon -c /home/thoht/.homeassistant/appdaemon/conf
2018-03-01 14:16:43.769643 INFO AppDaemon Version 3.0.0b3 starting
2018-03-01 14:16:43.770642 INFO Configuration read from: /home/thoht/.homeassistant/appdaemon/conf/appdaemon.yaml
2018-03-01 14:16:43.774367 INFO AppDaemon: Starting Apps
2018-03-01 14:16:43.784695 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2018-03-01 14:16:43.849581 INFO AppDaemon: HASS: HASS Plugin Initializing
2018-03-01 14:16:43.851024 INFO AppDaemon: HASS: HASS Plugin initialization complete
2018-03-01 14:16:43.852081 INFO Starting Dashboards
2018-03-01 14:16:43.879434 INFO API is disabled
2018-03-01 14:16:46.116975 INFO AppDaemon: HASS: Connected to Home Assistant 0.64.1
2018-03-01 14:16:46.600870 INFO AppDaemon: Got initial state from namespace default
2018-03-01 14:16:48.529244 INFO AppDaemon: Reading config
2018-03-01 14:16:48.677357 INFO AppDaemon: /home/thoht/.homeassistant/appdaemon/apps/foscam.yaml added or modified
2018-03-01 14:16:48.678466 INFO AppDaemon: /home/thoht/.homeassistant/appdaemon/apps/foscam.yaml added or modified
2018-03-01 14:16:48.679475 INFO AppDaemon: App 'foscam' added
2018-03-01 14:16:48.680694 INFO AppDaemon: Adding /home/thoht/.homeassistant/appdaemon/apps to module import path
2018-03-01 14:16:48.682634 INFO AppDaemon: Found module /home/thoht/.homeassistant/appdaemon/apps/foscam.py
2018-03-01 14:16:48.684291 INFO AppDaemon: Loading Module: /home/thoht/.homeassistant/appdaemon/apps/foscam.py
2018-03-01 14:16:48.755821 INFO AppDaemon: Initializing app foscam using class foscam from module foscam
2018-03-01 14:16:50.064814 WARNING AppDaemon: foscam: Entity sensor.foscam_motion not found in AppDaemon
2018-03-01 14:16:50.491190 ERROR foscam: one of the arguments has the wrong type
2018-03-01 14:16:50.497374 ERROR foscam: one of the arguments has the wrong type
2018-03-01 14:16:50.502907 INFO foscam:  App started without errors
2018-03-01 14:16:50.504005 WARNING AppDaemon: foscam: Entity sensor.foscam_last_error not found in AppDaemon
2018-03-01 14:16:50.613569 INFO AppDaemon: App initialization complete
2018-03-01 14:16:53.224907 WARNING AppDaemon: foscam: Entity sensor.foscam_motion not found in AppDaemon
2018-03-01 14:16:53.300445 WARNING AppDaemon: foscam: Entity sensor.foscam_sound_alarm not found in AppDaemon
2018-03-01 14:16:53.413495 WARNING AppDaemon: foscam: Entity sensor.foscam_recording not found in AppDaemon
```

**Comment by nlienard** [comment]
After setting the good model, still got error:

```
thoht@osmc:~/.homeassistant/appdaemon/conf$ appdaemon -c /home/thoht/.homeassistant/appdaemon/conf
2018-03-01 14:25:11.638884 INFO AppDaemon Version 3.0.0b3 starting
2018-03-01 14:25:11.639773 INFO Configuration read from: /home/thoht/.homeassistant/appdaemon/conf/appdaemon.yaml
2018-03-01 14:25:11.642589 INFO AppDaemon: Starting Apps
2018-03-01 14:25:11.651578 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2018-03-01 14:25:11.709393 INFO AppDaemon: HASS: HASS Plugin Initializing
2018-03-01 14:25:11.710720 INFO AppDaemon: HASS: HASS Plugin initialization complete
2018-03-01 14:25:11.711683 INFO Starting Dashboards
2018-03-01 14:25:11.736138 INFO API is disabled
2018-03-01 14:25:11.760017 INFO AppDaemon: HASS: Connected to Home Assistant 0.64.1
2018-03-01 14:25:11.896982 INFO AppDaemon: Got initial state from namespace default
2018-03-01 14:25:14.145749 INFO AppDaemon: Reading config
2018-03-01 14:25:14.277841 INFO AppDaemon: /home/thoht/.homeassistant/appdaemon/apps/foscam.yaml added or modified
2018-03-01 14:25:14.278559 INFO AppDaemon: /home/thoht/.homeassistant/appdaemon/apps/foscam.yaml added or modified
2018-03-01 14:25:14.279079 INFO AppDaemon: App 'foscam' added
2018-03-01 14:25:14.279815 INFO AppDaemon: Adding /home/thoht/.homeassistant/appdaemon/apps to module import path
2018-03-01 14:25:14.280764 INFO AppDaemon: Found module /home/thoht/.homeassistant/appdaemon/apps/foscam.py
2018-03-01 14:25:14.281498 INFO AppDaemon: Loading Module: /home/thoht/.homeassistant/appdaemon/apps/foscam.py
2018-03-01 14:25:14.351022 INFO AppDaemon: Initializing app foscam using class foscam from module foscam
2018-03-01 14:25:15.617555 ERROR foscam: one of the arguments has the wrong type
2018-03-01 14:25:15.623681 ERROR foscam: one of the arguments has the wrong type
2018-03-01 14:25:15.629041 INFO foscam:  App started without errors
2018-03-01 14:25:15.744745 INFO AppDaemon: App initialization complete




2018-03-01 14:26:16.060679 WARNING foscam: Failed to snap picture
```

**Comment by nlienard** [comment]
Ok i found 2 variables not set in foscal.yaml and now looks good:

```
thoht@osmc:~/.homeassistant/appdaemon/conf$ appdaemon -c /home/thoht/.homeassistant/appdaemon/conf
2018-03-01 15:23:50.979529 INFO AppDaemon Version 3.0.0b3 starting
2018-03-01 15:23:50.980784 INFO Configuration read from: /home/thoht/.homeassistant/appdaemon/conf/appdaemon.yaml
2018-03-01 15:23:50.984135 INFO AppDaemon: Starting Apps
2018-03-01 15:23:50.994610 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2018-03-01 15:23:51.054662 INFO AppDaemon: HASS: HASS Plugin Initializing
2018-03-01 15:23:51.056414 INFO AppDaemon: HASS: HASS Plugin initialization complete
2018-03-01 15:23:51.057847 INFO Starting Dashboards
2018-03-01 15:23:51.081566 INFO API is disabled
2018-03-01 15:23:51.106303 INFO AppDaemon: HASS: Connected to Home Assistant 0.64.1
2018-03-01 15:23:51.245966 INFO AppDaemon: Got initial state from namespace default
2018-03-01 15:23:53.488725 INFO AppDaemon: Reading config
2018-03-01 15:23:53.645010 INFO AppDaemon: /home/thoht/.homeassistant/appdaemon/apps/foscam.yaml added or modified
2018-03-01 15:23:53.646173 INFO AppDaemon: /home/thoht/.homeassistant/appdaemon/apps/foscam.yaml added or modified
2018-03-01 15:23:53.647154 INFO AppDaemon: App 'foscam' added
2018-03-01 15:23:53.648341 INFO AppDaemon: Adding /home/thoht/.homeassistant/appdaemon/apps to module import path
2018-03-01 15:23:53.649942 INFO AppDaemon: Found module /home/thoht/.homeassistant/appdaemon/apps/foscam.py
2018-03-01 15:23:53.651183 INFO AppDaemon: Loading Module: /home/thoht/.homeassistant/appdaemon/apps/foscam.py
2018-03-01 15:23:53.728965 INFO AppDaemon: Initializing app foscam using class foscam from module foscam
2018-03-01 15:23:54.741751 INFO foscam:  App started without errors
2018-03-01 15:23:54.854922 INFO AppDaemon: App initialization complete
```

**Comment by ReneTode** [comment]
glad you figured it out.
sorry i missed this. (for others that read this: open a topic on the forum.)
